version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file: .env
    volumes:
      - .:/var/www/robots
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
