version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/robots
    depends_on:
      - db
      - redis
    command: bundle exec puma -C config/puma.rb
  redis:
    image: redis
    ports:
      - 6379
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
